apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rapidjefs-com-tls
spec:
  secretName: rapidjefs-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rapidjefs.com
  dnsNames:
    - rapidjefs.com
    - www.rapidjefs.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rapidjefs.com
          - www.rapidjefs.com
